export { default as Facebook } from './icons/Name=facebook.svg'
export { default as Google } from './icons/Name=Google.svg'
export { default as Instagram } from './icons/Name=Instagram.svg'
export { default as LinkedIn } from './icons/Name=LinkedIn.svg'
export { default as Location } from './icons/Name=Location.svg'
export { default as Search } from './icons/Name=Search.svg'
export { default as Twitter } from './icons/Name=Twitter.svg'
export { default as excel } from './icons/excel.svg'
export { default as VNFlag } from './icons/VNFlag.webp'

// Logo
export { default as logo } from './logo/logo.svg'
export { default as cpLogo } from './logo/cpLogo.svg' 
export { default as companyLogoDefault } from './logo/companyLogoDefault.png'
export { default as vnpay } from './logo/vnpay.png'
export { default as flash } from './logo/flash.webp'

export { default as avatar } from './avatar/avatar.svg' 

export { default as bannerChild } from './background/banner_0.png'
export { default as banner } from './background/banner.png'
export { default as cvtmp } from './background/cvtmp.png'
export { default as companyCoverDefault } from './background/companyCoverDefault.jpg'
export { default as bgCv } from './background/bgCv.jpg'
export { default as bgAuth } from './background/bgAuth.png'
export { default as bgLogin } from './background/bgLogin.svg'
export { default as chart } from './background/chart.svg'
export { default as payment_success } from './background/payment_success.svg'
export { default as sendOpt } from './background/sendOtp.svg'
export { default as error } from './background/error.svg'
export { default as forgotPassword } from './background/forgotPassword.svg'
export { default as bgEmptyService } from './background/emptyService.svg'
export { default as company } from './background/company.svg'
export { default as bgSignupHr } from './background/bgSignupHr.svg'
export { default as emptyChat } from './background/emptyChat.png'
export { default as empty } from './background/empty.svg'
export { default as package_detail_banner } from './background/detail_package_banner.png'
export { default as lineBanner } from './background/line_banner.svg'
export { default as bgGrid } from './background/bg_grid_auth.svg'
export { default as Employer } from './background/bussiness.webp'
export { default as mascot_empty } from './background/mascot_empty.webp'
export { default as notification_empty } from './background/notification_empty.webp'
export { default as Candidate } from './background/student.webp'

