export { default as ArrowLeft } from './icons/ArrowLeft.svg'
export { default as ArrowRight } from './icons/Name=Arrow Right.svg'
export { default as At } from './icons/Name=At.svg'
export { default as Attachment } from './icons/Name=Attachment.svg'
export { default as Bold } from './icons/Name=Bold.svg'
export { default as Business } from './icons/Name=Business.svg'
export { default as Calendar } from './icons/Name=Calendar.svg'
export { default as Check } from './icons/Name=Check.svg'
export { default as ChevronDown } from './icons/Name=Chevron Down.svg'
export { default as ChevronLeft } from './icons/Name=Chevron Left.svg'
export { default as ChevronRight } from './icons/Name=Chevron Right.svg'
export { default as ChevronUp } from './icons/Name=Chevron Up.svg'
export { default as CircleCheck } from './icons/Name=Circle Check.svg'
export { default as Clock } from './icons/Name=Clock.svg'
export { default as Close } from './icons/Name=Close.svg'
export { default as Coffee } from './icons/Name=Coffee.svg'
export { default as Commute } from './icons/Name=Commute.svg'
export { default as Company } from './icons/Name=Company.svg'
export { default as Delete } from './icons/Name=Delete.svg'
export { default as Design } from './icons/Name=Design.svg'
export { default as Dollar } from './icons/Name=dollar.svg'
export { default as Down } from './icons/Name=Down.svg'
export { default as DragHandle } from './icons/Name=drag handle.svg'
export { default as Edit } from './icons/Name=Edit.svg'
export { default as Email } from './icons/Name=Email.svg'
export { default as Emoji } from './icons/Name=Emoji.svg'
export { default as Engineering } from './icons/Name=Engineering.svg'
export { default as Eye2 } from './icons/Name=Eye 2.svg'
export { default as Eye } from './icons/Name=Eye.svg'
export { default as Facebook } from './icons/Name=facebook.svg'
export { default as Filter } from './icons/Name=Filter.svg'
export { default as Finance } from './icons/Name=Finance.svg'
export { default as Fire } from './icons/Name=Fire.svg'
export { default as Flag } from './icons/Name=Flag.svg'
export { default as Google } from './icons/Name=Google.svg'
export { default as Grid } from './icons/Name=Grid.svg'
export { default as Hamburger } from './icons/Name=Hamburger.svg'
export { default as Healthcare } from './icons/Name=Healthcare.svg'
export { default as Help } from './icons/Name=Help.svg'
export { default as Home } from './icons/Name=Home.svg'
export { default as HR } from './icons/Name=HR.svg'
export { default as Image } from './icons/Name=Image.svg'
export { default as Info } from './icons/Name=Info.svg'
export { default as Instagram } from './icons/Name=Instagram.svg'
export { default as Interview } from './icons/Name=Interview.svg'
export { default as Italic } from './icons/Name=Italic.svg'
export { default as JobApplication } from './icons/Name=Job Application.svg'
export { default as JobListing } from './icons/Name=Job Listing.svg'
export { default as Language } from './icons/Name=Language.svg'
export { default as Link } from './icons/Name=Link.svg'
export { default as LinkedIn } from './icons/Name=LinkedIn.svg'
export { default as ListNumbers } from './icons/Name=List Numbers.svg'
export { default as ListUnordered } from './icons/Name=List Unordered.svg'
export { default as List } from './icons/Name=List.svg'
export { default as Location } from './icons/Name=Location.svg'
export { default as Logout } from './icons/Name=Logout.svg'
export { default as Marketing } from './icons/Name=Marketing.svg'
export { default as Messages } from './icons/Name=Messages.svg'
export { default as Minus } from './icons/Name=Minus.svg'
export { default as MoreVertical } from './icons/Name=More Vertical.svg'
export { default as More } from './icons/Name=More.svg'
export { default as NotificationEmpty } from './icons/Name=Notification Empty.svg'
export { default as NotificationNew } from './icons/Name=Notification New.svg'
export { default as Password } from './icons/Name=Password.svg'
export { default as Pencil } from './icons/Name=Pencil.svg'
export { default as PerksBenefits } from './icons/Name=Perks & Benefits.svg'
export { default as Phone } from './icons/Name=Phone.svg'
export { default as Pin } from './icons/Name=Pin.svg'
export { default as Plus } from './icons/Name=Plus.svg'
export { default as Sales } from './icons/Name=Sales.svg'
export { default as Save } from './icons/Name=Save.svg'
export { default as Search } from './icons/Name=Search.svg'
export { default as Send } from './icons/Name=Send.svg'
export { default as Settings } from './icons/Name=Settings.svg'
export { default as Share } from './icons/Name=Share.svg'
export { default as SignUp } from './icons/Name=Sign Up.svg'
export { default as Solidarity1 } from './icons/Name=solidarity 1.svg'
export { default as Sort } from './icons/Name=Sort.svg'
export { default as Star } from './icons/Name=Star.svg'
export { default as StarFilled } from './icons/Name=Star-Filled.svg'
export { default as Summit } from './icons/Name=Summit.svg'
export { default as Tech } from './icons/Name=Tech.svg'
export { default as ThumbDown } from './icons/Name=Thumb Down.svg'
export { default as ThumbUp } from './icons/Name=Thumb Up.svg'
export { default as Twitter } from './icons/Name=Twitter.svg'
export { default as Up } from './icons/Name=Up.svg'
export { default as User } from './icons/Name=User.svg'
export { default as Vacation } from './icons/Name=Vacation.svg'
export { default as Video } from './icons/Name=Video.svg'
export { default as Web } from './icons/Name=Web.svg'
export { default as VNFlag } from './icons/VNFlag.webp'

// Logo
export { default as logo } from './logo/logo.svg'
export { default as cpLogo } from './logo/cpLogo.svg' 
export { default as companyLogoDefault } from './logo/companyLogoDefault.png'

export { default as avatar } from './avatar/avatar.svg' 

export { default as bgAuth } from './background/bgAuth.png'
export { default as bgLogin } from './background/bgLogin.svg'
export { default as bgEmptyService } from './background/emptyService.svg'
export { default as company } from './background/company.svg'
export { default as bgSignupHr } from './background/bgSignupHr.svg'
export { default as emptyChat } from './background/emptyChat.png'
export { default as empty } from './background/empty.svg'
export { default as package_detail_banner } from './background/detail_package_banner.png'
export { default as lineBanner } from './background/line_banner.svg'
export { default as bgGrid } from './background/bg_grid_auth.svg'
export { default as Employer } from './background/bussiness.webp'
export { default as mascot_empty } from './background/mascot_empty.webp'
export { default as notification_empty } from './background/notification_empty.webp'
export { default as Candidate } from './background/student.webp'

