import { ROLE } from "../constants/enum";
import { RouteBase } from "../constants/routeUrl";
import { AdminLayout, HRLayout } from "../layouts";
import {
  CompanyPage,
  CreateCVPage,
  CvManagementPage,
  FindJobPage,
  HomePage,
  SignInPage,
  SignUpPage,
  SignUpHrPage,
  NotFoundPage,
  ProfileSettingPage,
  ConnectPage,
  JobDetailsPage,
  CompanyDetailPage,
  CompanySearchPage,
  WishListPage,
  ViewedResumePage,
  ChangePasswordPage,
  VerifyAccountPage,
  ForgotPasswordPage,
  MyCvPage,
  EditCVPage,
  VerifyResultPage,
  ResetPasswordPage,
} from "../pages";
import {
  ChatPage,
  CheckoutPage,
  CvManagementHrPage,
  JobDetailPage,
  MyCompanyPage,
  MyPackagePage,
  OverViewPage,
  PackageDetailPage,
  PackagePage,
  PostJobPage,
  ProfileHrPage,
  RecruitmentReportPage,
  ReturnPaymentPage,
  VerifyPage,
} from "../hr_pages";
import {
  CategoryManagementPage,
  CompanyManagementPage,
  CreateUserPage,
  CvThemePage,
  NotifyManagementPage,
  OverViewAdminPage,
  PackageManagementPage,
  PostManageMentPage,
  ProfileAdminPage,
  ReportManagementPage,
  RevenueManagementPage,
  UserDetailPage,
  UserManagementPage,
} from "../admin_page";

const Routes = [
  {
    path: RouteBase.Home,
    component: HomePage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: RouteBase.SignIn,
    component: SignInPage,
    permissionAllow: [ROLE.ALL],
    layout: null,
  },
  {
    path: RouteBase.SignUp,
    component: SignUpPage,
    permissionAllow: [ROLE.ALL],
    layout: null,
  },
  {
    path: RouteBase.SignUpHr,
    component: SignUpHrPage,
    permissionAllow: [ROLE.ALL],
    layout: null,
  },
  {
    path: RouteBase.ForgotPassword,
    component: ForgotPasswordPage,
    permissionAllow: [ROLE.ALL],
    layout: null,
  },
  {
    path: RouteBase.Job,
    component: FindJobPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: RouteBase.JobDetail,
    component: JobDetailsPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: RouteBase.CVTemplate,
    component: CvManagementPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: `${RouteBase.CVTemplate}/:id`,
    component: CreateCVPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: `${RouteBase.CVTemplate}/:id/edit/:cv_id`,
    component: EditCVPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: RouteBase.MyCv,
    component: MyCvPage,
    permissionAllow: [ROLE.CANDIDATE],
  },
  {
    path: RouteBase.Company,
    component: CompanyPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: RouteBase.CompanySearch,
    component: CompanySearchPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: `${RouteBase.Company}/:id`,
    component: CompanyDetailPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: RouteBase.Connect,
    component: ConnectPage,
    permissionAllow: [ROLE.ALL],
    layout: null,
  },
  {
    path: RouteBase.Profile,
    component: ProfileSettingPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: RouteBase.ChangePassword,
    component: ChangePasswordPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: RouteBase.ResetPassword,
    component: ResetPasswordPage,
    permissionAllow: [ROLE.ALL],
    layout: null,
  },
  {
    path: RouteBase.WishList,
    component: WishListPage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: RouteBase.ViewedResume,
    component: ViewedResumePage,
    permissionAllow: [ROLE.ALL],
  },
  {
    path: RouteBase.VerifyAccount,
    component: VerifyAccountPage,
    permissionAllow: [ROLE.CANDIDATE],
  },
  {
    path: RouteBase.VerifyResult,
    component: VerifyResultPage,
    permissionAllow: [ROLE.CANDIDATE],
  },
  {
    path: "*",
    component: NotFoundPage,
    permissionAllow: [ROLE.ALL],
    layout: null,
  },

  // HR Routes
  {
    path: RouteBase.HROverview,
    component: OverViewPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: RouteBase.HRJobs,
    component: PostJobPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: `${RouteBase.HRJobs}/:id`,
    component: JobDetailPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: RouteBase.HRProfile,
    component: ProfileHrPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: RouteBase.HRChat,
    component: ChatPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: RouteBase.HRPackage,
    component: PackagePage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: `${RouteBase.HRPackage}/:id`,
    component: PackageDetailPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: RouteBase.HRMyPackage,
    component: MyPackagePage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: RouteBase.HRCheckout,
    component: CheckoutPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: RouteBase.HRReturnPayment,
    component: ReturnPaymentPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },

  {
    path: RouteBase.HRRecruitmentReport,
    component: RecruitmentReportPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: RouteBase.HRVerify,
    component: VerifyPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: RouteBase.HRMyCompany,
    component: MyCompanyPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },
  {
    path: RouteBase.HRCvManagement,
    component: CvManagementHrPage,
    permissionAllow: [ROLE.EMPLOYER],
    layout: HRLayout,
  },

  // ADMIN Routes
  {
    path: RouteBase.AdminOverview,
    component: OverViewAdminPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminNotifyManagement,
    component: NotifyManagementPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminPackageManagement,
    component: PackageManagementPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminPostManagement,
    component: PostManageMentPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminCompanyManagement,
    component: CompanyManagementPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminUserManagement,
    component: UserManagementPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: `${RouteBase.AdminUserManagement}/:id`,
    component: UserDetailPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminCreateUser,
    component: CreateUserPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminRevenueManagement,
    component: RevenueManagementPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminCategory,
    component: CategoryManagementPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminProfile,
    component: ProfileAdminPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminCvTheme,
    component: CvThemePage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
  {
    path: RouteBase.AdminReport,
    component: ReportManagementPage,
    permissionAllow: [ROLE.ADMIN],
    layout: AdminLayout,
  },
];

export default Routes;
