export const RouteBase = {
  // All
  Home: "/",

  SignIn: "/sign-in",
  SignUp: "/sign-up",
  SignUpHr: "/sign-up-hr",
  ForgotPassword: "/forgot-password",

  Job: "/job",
  JobDetail: "/job/:id",
  CVTemplate: "/cv-template",
  Company: "/company",
  CompanySearch: "/company/search",
  Connect: "/connect",
  Profile: "/profile",
  ChangePassword: "/profile/change-password",
  Connect: "/connect",
  WishList: "/wishlist",
  ViewedResume: "/viewed-resume",
  VerifyAccount: "/verify-account",
  VerifyResult: "/verify-result",
  MyCv: "/my-cv",
  ResetPassword: "/reset-password",

  // HR
  HROverview: "/hr",
  HRJobs: "/hr/jobs",
  HRApplicants: "/hr/applicants",
  HRProfile: "/hr/profile",
  HRChat: "/hr/chat",
  HRPackage: "/hr/package",
  HRMyPackage: "/hr/my-package",
  HRCheckout: "/hr/checkout",
  HRReturnPayment: "/hr/return-payment",
  HRRecruitmentReport: "/hr/recruitment-report",
  HRMyCompany: "/hr/my-company",
  HRVerify: "/hr/verify",
  HRCvManagement: "/hr/cv-management",

  // ADMIN
  AdminOverview: "/admin",
  AdminProfile: "/admin/profile",
  AdminPostManagement: "/admin/post-management",
  AdminCompanyManagement: "/admin/company-management",
  AdminPackageManagement: "/admin/package-management",
  AdminUserManagement: "/admin/user-management",
  AdminCreateUser: "/admin/user-management/create",
  AdminNotifyManagement: "/admin/notify-management",
  AdminRevenueManagement: "/admin/revenue-management",
  AdminProfile: "/admin/profile",
  AdminCategory: "/admin/category",
  AdminCvTheme: "/admin/cv-theme",
  AdminReport: "/admin/report",
};
