export {default as CategoryItem } from './CategoryItem'
export {default as Logo } from './Logo'
export {default as DefautAvatar } from './DefautAvatar'
export {default as CVItem } from './CVItem'
export {default as ConfirmDelete } from './ConfirmDelete'